# Generated by Django 2.2.1 on 2019-06-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_request_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email_to'),
        ),
    ]
